import { ensureDir } from '@std/fs';
import { basename, join } from '@std/path';
import { green, red } from '@std/fmt/colors';

// This value is changed in the release pipeline
const LIMETTE_VERSION = '0.2.3';

const LIT_VERSION = '3.2.1';
const VITE_VERSION = '8.0.0';
const TAILWIND_VERSION = '4.3.3';

type Runtime = 'deno' | 'node';

function option(name: string) {
  const prefix = `--${name}=`;
  return Deno.args.find((argument) => argument.startsWith(prefix))?.slice(
    prefix.length,
  );
}

function choose(
  label: string,
  choices: readonly string[],
  defaultChoice: string,
) {
  console.log(`${label}:`);
  for (const choice of choices) {
    console.log(`${choice === defaultChoice ? '>' : ' '} ${choice}`);
  }
  const answer = prompt(`Choose ${label.toLowerCase()}`, defaultChoice);
  return choices.find((choice) =>
    choice.toLowerCase() === answer?.trim().toLowerCase()
  ) ?? defaultChoice;
}

function fail(message: string): never {
  console.error(`${red('Error:')} ${message}`);
  Deno.exit(1);
}

const projectName = Deno.args.find((argument) => !argument.startsWith('--')) ??
  prompt('Your project name?');
if (typeof projectName !== 'string' || projectName.length < 1) {
  fail('Invalid project name!');
}

const runtimeOption = option('runtime')?.toLowerCase();
if (runtimeOption && runtimeOption !== 'deno' && runtimeOption !== 'node') {
  fail('Runtime must be "deno" or "node".');
}
const runtime = (runtimeOption ??
  choose('Runtime', ['Deno', 'Node'], 'Deno').toLowerCase()) as Runtime;

const tailwindOption = option('tailwind')?.toLowerCase();
if (
  tailwindOption && !['yes', 'no', 'true', 'false'].includes(tailwindOption)
) {
  fail('Tailwind must be "yes" or "no".');
}
const useTailwind = tailwindOption
  ? tailwindOption === 'yes' || tailwindOption === 'true'
  : choose('Use Tailwind CSS?', ['Yes', 'No'], 'Yes') === 'Yes';

const projectPath = join(Deno.cwd(), projectName);
const islandsPath = join(projectPath, 'islands');
const routesPath = join(projectPath, 'routes');
const publicPath = join(projectPath, 'public');

await ensureDir(islandsPath);
await ensureDir(routesPath);
await ensureDir(publicPath);

const gitignore = `
# dotenv environment variable files
.env

node_modules

# Vite build directory
dist/
`;

const packageJson = {
  name: basename(projectName),
  private: true,
  type: 'module',
  scripts: {
    dev: 'vite',
    build: 'vite build',
    start: runtime === 'deno' ? 'deno run -A main.ts' : 'node main.js',
  },
  dependencies: {
    '@limette/core': `^${LIMETTE_VERSION}`,
    lit: `^${LIT_VERSION}`,
  },
  devDependencies: {
    ...useTailwind
      ? {
        '@tailwindcss/vite': `^${TAILWIND_VERSION}`,
        tailwindcss: `^${TAILWIND_VERSION}`,
      }
      : {},
    vite: `^${VITE_VERSION}`,
  },
};

const appTs = `
import { App } from "@limette/core";

export const app = new App()
  .fsRoutes();
`;

const denoMain = `
import { serve } from "@limette/core/deno";
// @ts-ignore Generated by the production Vite build.
import handler from "./dist/server/entry.js";

await serve(handler, {
  port: Number(Deno.env.get("PORT") ?? 8000),
  staticFiles: {
    root: "./dist/client",
  },
});
`;

const nodeMain = `
import { serve } from "@limette/core/node";
import handler from "./dist/server/entry.js";

await serve(handler, {
  port: Number(process.env.PORT ?? 8000),
  staticFiles: {
    root: "./dist/client",
  },
});
`;

const viteConfigTs = `
${
  useTailwind
    ? 'import tailwindcss from "@tailwindcss/vite";\n'
    : ''
}import { defineConfig } from "vite";
import { limette } from "@limette/core/vite";

export default defineConfig({
  plugins: [
${useTailwind ? '    tailwindcss(),\n' : ''}    limette({
      app: "./app.ts",${
  useTailwind ? '\n      tailwind: "./tailwind.css",' : ''
}
    }),
  ],
});
`;

const counterClass = useTailwind ? ' class="text-lime-800 leading-[1.4]"' : '';
const counterIslandTs = `
/// <reference lib="dom" />

import { LitElement, html, css } from "lit";

export class Counter extends LitElement {
  declare count: number;
  declare name: string;

  static override styles = css\`
    :host {
      display: block;
      box-sizing: border-box;
      width: 100%;
      border: 1px solid #a3a3a3;
      border-radius: 8px;
      padding: 16px;
    }
    h2 {
      margin: 0 0 16px;
    }
    section {
      display: grid;
      grid-template-columns: 40px 1fr 40px;
      align-items: center;
      gap: 12px;
    }
    p {
      margin: 0;
      text-align: center;
    }
    button {
      min-height: 36px;
      border: 1px solid #a3a3a3;
      border-radius: 6px;
      background: white;
      font: inherit;
      cursor: pointer;
    }
  \`;

  static override properties = {
    name: { type: String },
    count: { type: Number },
  };

  constructor() {
    super();
    this.name = "Somebody";
    this.count = 0;
  }

  override render() {
    return html\`
      <div${counterClass}>
        <h2>Hello, <span>\${this.name}</span></h2>
        <section>
          <button type="button" @click=\${() => this.count--}>-</button>
          <p>Count: \${this.count}</p>
          <button type="button" @click=\${() => this.count++}>+</button>
        </section>
      </div>
    \`;
  }
}

if (!customElements.get("island-counter")) {
  customElements.define("island-counter", Counter);
}
`;

const _appRouteTs = `
import { AppComponent } from "@limette/core";
import { html } from "lit";

export default class App extends AppComponent {
  override render() {
    return html\`<!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Limette</title>
        \${this.assets.styles}
      </head>
      <body>
        \${this.page}
        <!-- -->
        \${this.assets.scripts}
      </body>
    </html>\`;
  }
}
`;

const headingClass = useTailwind
  ? ' class="text-[37px] font-semibold tracking-tight"'
  : '';
const indexRouteTs = `
import { PageComponent } from "@limette/core";
import { html, css } from "lit";
import { Counter } from "../islands/counter.ts";

export default class Home extends PageComponent {
  static override islands = {
    "island-counter": Counter,
  };

  static override styles = css\`
    .container {
      display: flex;
      align-items: center;
      flex-direction: column;
      text-align: center;
      padding: 32px 16px;
      font-family: sans-serif;
    }
    h1 {
      margin: 0 0 24px;
    }
    .content {
      display: grid;
      gap: 20px;
      width: 100%;
      max-width: 320px;
    }
    .content > p {
      margin: 0;
    }
    island-counter {
      display: block;
      width: 100%;
    }
  \`;

  override render() {
    return html\`
      <section class="container">
        <h1${headingClass}>Limette</h1>
        <div class="content">
          <p>This is SSR content.</p>
          <island-counter name="Iris"></island-counter>
          <section>
            <a href="/foo">To foo</a>
          </section>
        </div>
      </section>
    \`;
  }
}
`;

const fooRouteTs = `
import { PageComponent, type Handlers } from "@limette/core";
import { html, css } from "lit";

export const handler: Handlers = {
  POST(_ctx) {
    return new Response("Response for POST request!");
  },
};

export default class Foo extends PageComponent {
  static override styles = css\`
    .container {
      font-family: sans-serif;
      display: flex;
      align-items: center;
      flex-direction: column;
      text-align: center;
      padding-top: 24px;
    }
    .content {
      max-width: 320px;
    }
  \`;

  override render() {
    return html\`
      <lmt-head>
        <title>Foo</title>
      </lmt-head>
      <section class="container">
        <h1>Limette</h1>
        <div class="content">
          <p>Foo page.</p>
          <section>
            <a href="/">To home</a>
          </section>
        </div>
      </section>
    \`;
  }
}
`;

const tailwindCss = `@import "tailwindcss";\n`;

await Deno.writeTextFile(join(projectPath, '.gitignore'), gitignore);
await Deno.writeTextFile(
  join(projectPath, 'package.json'),
  `${JSON.stringify(packageJson, null, 2)}\n`,
);
await Deno.writeTextFile(join(projectPath, 'app.ts'), appTs);
await Deno.writeTextFile(
  join(projectPath, runtime === 'deno' ? 'main.ts' : 'main.js'),
  runtime === 'deno' ? denoMain : nodeMain,
);
await Deno.writeTextFile(join(projectPath, 'vite.config.ts'), viteConfigTs);
await Deno.writeTextFile(
  join(projectPath, 'islands/counter.ts'),
  counterIslandTs,
);
await Deno.writeTextFile(join(projectPath, 'routes/_app.ts'), _appRouteTs);
await Deno.writeTextFile(join(projectPath, 'routes/index.ts'), indexRouteTs);
await Deno.writeTextFile(join(projectPath, 'routes/foo.ts'), fooRouteTs);
if (useTailwind) {
  await Deno.writeTextFile(join(projectPath, 'tailwind.css'), tailwindCss);
}

if (Deno.env.get('LIMETTE_INIT_SKIP_INSTALL') !== '1') {
  const executable = runtime === 'deno'
    ? 'deno'
    : Deno.build.os === 'windows'
    ? 'npm.cmd'
    : 'npm';
  const output = await new Deno.Command(executable, {
    args: ['install'],
    cwd: projectPath,
    stdout: 'piped',
    stderr: 'piped',
  }).output();
  if (!output.success) {
    console.error(new TextDecoder().decode(output.stderr));
    Deno.exit(output.code);
  }
}

const installCommand = runtime === 'deno' ? 'deno install' : 'npm install';
const devCommand = runtime === 'deno' ? 'deno task dev' : 'npm run dev';
console.log(`${green('Your project is ready!')} 🎉\n`);
console.log(`  cd ${projectName}`);
console.log(`  ${installCommand}`);
console.log(`  ${devCommand}`);
