import { ensureDir } from '@std/fs';
import { join } from '@std/path';
import { green, red } from '@std/fmt/colors';

// This value is changed in the release pipeline
const LIMETTE_VERSION = '0.2.3';

const LIT_VERSION = '3.2.1';
const VITE_VERSION = '8.0.0';

const projectName = Deno.args[0] ?? prompt('Your project name?');
if (typeof projectName !== 'string' || projectName?.length < 1) {
  console.log(`${red('Error:')} Invalid project name!`);
  Deno.exit();
}
const projectPath = join(Deno.cwd(), projectName as string);
const islandsPath = join(projectPath, 'islands');
const routesPath = join(projectPath, 'routes');
const publicPath = join(projectPath, 'public');

// root folder
await ensureDir(projectPath);
// islands folder
await ensureDir(islandsPath);
// routes folder
await ensureDir(routesPath);
// public folder
await ensureDir(publicPath);

const gitignore = `
# dotenv environment variable files
.env

node_modules

# Vite build directory
dist/
`;

const denoJson = `
{
  "tasks": {
    "dev": "deno run -A npm:vite@^${VITE_VERSION} --config vite.config.ts --host 127.0.0.1",
    "build": "deno run -A npm:vite@^${VITE_VERSION} --config vite.config.ts build",
    "start": "deno run -A main.ts"
  },
  "imports": {
    "@limette/core": "npm:@limette/core@^${LIMETTE_VERSION}",
    "@limette/core/deno": "npm:@limette/core@^${LIMETTE_VERSION}/deno",
    "@limette/core/vite": "npm:@limette/core@^${LIMETTE_VERSION}/vite",
    "/lit": "npm:/lit@^${LIT_VERSION}/",
    "lit": "npm:lit@^${LIT_VERSION}",
    "vite": "npm:vite@^${VITE_VERSION}"
  },
  "compilerOptions": {
    "lib": [
      "dom",
      "dom.iterable",
      "dom.asynciterable",
      "deno.ns",
      "deno.unstable"
    ]
  },
  "fmt": {
    "singleQuote": true
  },
  "nodeModulesDir": "auto",
  "lock": false
}
`;

const appTs = `
import { App } from "@limette/core";

export const app = new App()
  .fsRoutes();
`;

const mainTs = `
import { serve } from "@limette/core/deno";
// @ts-ignore Generated by the production Vite build.
import handler from "./dist/server/entry.js";

const port = Deno.env.get("PORT");

await serve(handler, {
  port: port ? Number(port) : undefined,
  staticFiles: {
    root: "./dist/client",
  },
});
`;

const viteConfigTs = `
import { defineConfig } from "vite";
import { limette } from "@limette/core/vite";

export default defineConfig({
  plugins: [
    limette({
      app: "./app.ts",
    }),
  ],
});
`;

const counterIslandTs = `
import { LitElement, html, css } from "lit";

export class Counter extends LitElement {
  declare count: number;
  declare name: string;

  static override styles = css\`
    :host {
      display: block;
      border: 2px solid green;
      padding: 8px;
    }
    section {
      display: flex;
      justify-content: space-between;
    }
  \`;

  static override properties = {
    name: { type: String },
    count: { type: Number },
  };

  constructor() {
    super();
    this.name = "Somebody";
    this.count = 0;
  }

  override render() {
    return html\`
      <div>
        <h2>Hello,<span>\${this.name}</span></h2>
        <section>
          <button type="button" @click=\${() => this.count--}>-</button>
          <p>Count: \${this.count}</p>
          <button type="button" @click=\${() => this.count++}>+</button>
        </section>
      </div>
    \`;
  }
}

if (!customElements.get("island-counter")) {
  customElements.define("island-counter", Counter);
}
`;

const _appRouteTs = `
import { AppComponent } from "@limette/core";
import { html } from "lit";

export default class App extends AppComponent {
  override render() {
    return html\`<!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Limette</title>
        \${this.assets.styles}
      </head>
      <body>
        \${this.page}
        <!-- -->
        \${this.assets.scripts}
      </body>
    </html>\`;
  }
}
`;

const indexRouteTs = `
import { PageComponent } from "@limette/core";
import { html, css } from "lit";
import { Counter } from "../islands/counter.ts";

export default class Home extends PageComponent {
  static override islands = {
    "island-counter": Counter,
  };

  static override styles = css\`
    .container {
      display: flex;
      align-items: center;
      flex-direction: column;
      text-align: center;
      padding-top: 24px;
      font-family: sans-serif;
    }
    .content {
      max-width: 320px;
    }
  \`;

  override render() {
    return html\`
      <section class="container">
        <h1>Limette</h1>
        <div class="content">
          <p>This is SSR content.</p>
          <island-counter name="Iris"></island-counter>
          <section>
            <a href="/foo">To foo</a>
          </section>
        </div>
      </section>
    \`;
  }
}
`;

const fooRouteTs = `
import { PageComponent, type Handlers } from "@limette/core";
import { html, css } from "lit";

export const handler: Handlers = {
  POST(_ctx) {
    return new Response('Response for POST request!');
  },
};

export default class Foo extends PageComponent {
  static override styles = css\`
    .container {
      font-family: sans-serif;
      display: flex;
      align-items: center;
      flex-direction: column;
      text-align: center;
      padding-top: 24px;
    }
    .content {
      max-width: 320px;
    }
  \`;
  override render() {
    return html\`
      <lmt-head>
        <title>Foo</title>
      </lmt-head>
      <section class="container">
        <h1>Limette</h1>
        <div class="content">
          <p>Foo page.</p>
          <section>
            <a href="/">To home</a>
          </section>
        </div>
      </section>
    \`;
  }
}
`;

function removeEmptyLines(content: string) {
  return content
    .split('\n')
    .filter((line: string) => line.trim() !== '')
    .join('\n');
}

Deno.writeTextFileSync(join(projectPath, '.gitignore'), gitignore);
Deno.writeTextFileSync(
  join(projectPath, 'deno.json'),
  removeEmptyLines(denoJson),
);
Deno.writeTextFileSync(join(projectPath, 'app.ts'), appTs);
Deno.writeTextFileSync(join(projectPath, 'main.ts'), mainTs);
Deno.writeTextFileSync(join(projectPath, 'vite.config.ts'), viteConfigTs);
Deno.writeTextFileSync(
  join(projectPath, 'islands/counter.ts'),
  counterIslandTs,
);
Deno.writeTextFileSync(join(projectPath, 'routes/_app.ts'), _appRouteTs);
Deno.writeTextFileSync(
  join(projectPath, 'routes/index.ts'),
  indexRouteTs,
);
Deno.writeTextFileSync(
  join(projectPath, 'routes/foo.ts'),
  fooRouteTs,
);

// Install dependencies
if (Deno.env.get('LIMETTE_INIT_SKIP_INSTALL') !== '1') {
  const command = new Deno.Command('deno', {
    args: [
      'install',
      '--allow-scripts',
      '--config',
      join(projectName as string, 'deno.json'),
    ],
    stdout: 'piped',
    stderr: 'piped',
  });
  const output = await command.output();
  if (!output.success) {
    console.error(new TextDecoder().decode(output.stderr));
    Deno.exit(output.code);
  }
}

console.log(`${green('Your project is ready!')} 🎉`);
