import { serve } from '@limette/core/deno';
// @ts-ignore Generated by the production Vite build.
import handler from './dist/server/entry.js';

await serve(handler, {
  staticFiles: {
    root: await Deno.realPath(new URL('./dist/client/', import.meta.url)),
  },
});
