import { fileURLToPath } from 'node:url';
import { serve } from '@limette/core/node';
// @ts-ignore Generated by the production Vite build.
import handler from './dist/server/entry.js';

await serve(handler, {
  staticFiles: {
    root: fileURLToPath(new URL('./dist/client/', import.meta.url)),
  },
});
